### PR TITLE
Search in conversation

### LINKED ISSUE #99: Search in conversation
**Describe the task that needs to be done.**
Implement a search feature within the chat to allow users to search for historical message.

**Describe how a solution to your proposed task might look like (and any alternatives considered).**
Add a search pop up in the chat page which allow users enter their search keywords. Returns the corresponding search result in the chat page

**Notes**
- Possible future work

### PR DESCRIPTION
**Pull request by christopher-alba**
## Description
This PR allows users to search through past messages by using the newly added searchbar next to the name of the person you are chatting to.

resolves #99 

## How has this been tested?
Manual Testing

## Screenshots
Before searching
image

After searching
image

## Checklist
*(Leave blank if not applicable)*

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by Xiaoqi510 — COMMENTED** [review]
The search function looks great! But when try to I search for something, the search box is hidden a little bit. Need to do some css. 
Screen Shot 2022-03-28 at 8 05 35 PM

**Comment by christopher-alba** [comment]
> The search function looks great! But when try to I search for something, the search box is hidden a little bit. Need to do some css. Screen Shot 2022-03-28 at 8 05 35 PM

image
Heya thanks for pointing this out, hopefully the most recent commit fixes it.

**Review by Xiaoqi510 — APPROVED** [review]
LGTM!

**Comment by Xiaoqi510** [comment]
> > The search function looks great! But when try to I search for something, the search box is hidden a little bit. Need to do some css. Screen Shot 2022-03-28 at 8 05 35 PM
> 
> image Heya thanks for pointing this out, hopefully the most recent commit fixes it.

LGTM!

**Review by yuchendong13 — APPROVED** [review]
LGTM!

**Review by hpar461 — APPROVED** [review]
LGTM!

**Review by R055A — APPROVED** [review]

**Pull request merged**
