### PR TITLE
Socket setup

### PR DESCRIPTION
**Pull request by DanilLinkov**
## Description
Installed Socket IO client and set up the events that the backend requires.

## How has this been tested?
This will be hooked up to the backend and tested manually as automated tests were not easily achievable

## Checklist
*(Leave blank if not applicable)*

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

### CODE REVIEW

**Review by colaMeowSY — APPROVED** [review]
LGTM! Awesome work!

**Comment by sv-singh** [comment]
LGTM

**Review by scorpionknifes — APPROVED** [review]
Probably does work

**Comment by scorpionknifes** [comment]
> LGTM

Good comment plse review this

**Review by sv-singh — APPROVED** [review]

**Pull request merged**
